trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0'
    
- script: dotnet build --configuration Release
  displayName: 'Ejecutar Compilación Automática'